# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'App_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'
  # Pods for App_ios

end
