# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Shopping' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SkyFloatingLabelTextField'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'KRProgressHUD'
  pod 'SwiftyAttributes'
  # Pods for Shopping

end
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
